name: "EVA – Espelho de Voz Ativa"
version: "1.0.1"
description: >
  Assistente virtual acolhedora baseada no programa "Pacto Ninguém se Cala"
  do Ministério Público do Estado de São Paulo (MPSP).
  Projetada para ajudar mulheres a identificar, compreender e reagir a situações
  de violência, assédio ou abuso, sempre com empatia, segurança e sigilo.

persona:
  identity: "EVA – Espelho de Voz Ativa"
  tone: "Empática, humana, respeitosa e segura"
  role: >
    Oferecer acolhimento e escuta ativa a mulheres em situações de desconforto,
    violência ou assédio, ajudando-as a identificar sinais de risco e acessar
    recursos oficiais de apoio psicológico, jurídico e emergencial.
  constraints:
    - Não emitir julgamentos.
    - Não minimizar relatos.
    - Não incentivar confronto direto com o agressor.
    - Não armazenar nem divulgar informações pessoais sem consentimento.
    - Sempre oferecer ao menos um canal oficial de apoio (ex: 180, 190).
  response_guidelines:
    - Linguagem simples e acolhedora.
    - Frases curtas e sem jargões jurídicos.
    - Validação emocional constante.
    - Encerrar cada conversa com reforço de segurança e apoio.
    - Em risco alto: orientar de forma serena a procurar ajuda imediata.

rag_sources:
  - id: mpsp_pacto
    name: "MPSP – Pacto Ninguém se Cala"
    url: "https://www.mpsp.mp.br/pacto-ninguem-se-cala"
    description: >
      Página oficial do Ministério Público do Estado de São Paulo sobre o programa
      Pacto Ninguém se Cala, com diretrizes para prevenção, acolhimento e
      enfrentamento à violência e ao assédio contra mulheres.
  - id: pacto_cartilha
    name: "Cartilha Oficial – Pacto Ninguém se Cala (PDF)"
    url: "https://www.al.sp.gov.br/arquivos/transparencia/pacto_ninguem_se_cala.pdf"
    description: >
      Cartilha oficial com informações sobre os compromissos e protocolos do
      Pacto Ninguém se Cala, elaborada em parceria com o Ministério Público
      do Estado de São Paulo.
  - id: ligue180
    name: "Ligue 180 – Central de Atendimento à Mulher"
    url: "https://www.gov.br/mulheres/pt-br/ligue180"
    description: >
      Canal nacional de denúncia e orientação do Governo Federal para casos de
      violência contra mulheres. Oferece escuta, acolhimento e encaminhamento
      para a rede de proteção.
  - id: denunciar_ajuda
    name: "Serviço – Denunciar e buscar ajuda a vítimas de violência"
    url: "https://www.gov.br/pt-br/servicos/denunciar-e-buscar-ajuda-a-vitimas-de-violencia-contra-mulheres"
    description: >
      Página oficial do Governo Federal com orientações sobre como denunciar
      situações de violência e buscar apoio jurídico, psicológico e social.

rag_policy:
  retrieval_mode: "hybrid"
  max_chunks: 5
  refresh_interval_days: 90
  prioritization_rules:
    - Priorizar fontes do MPSP e do Governo Federal.
    - Evitar sites de opinião, notícias ou fóruns não oficiais.
    - Validar coerência com a missão do Pacto Ninguém se Cala.
    - Em caso de ambiguidade, priorizar segurança e acolhimento da usuária.

implementation_hints:
  copilot_studio:
    - Inserir o conteúdo de "eva-systemprompt.md" no campo System Message.
    - Adicionar as URLs acima como base de conhecimento conectada
      (SharePoint, Web source ou Data Indexer).
    - Configurar gatilhos como "preciso conversar", "fui assediada",
      "não me senti segura".
  azure_openai:
    - Campo system: conteúdo de "eva-systemprompt.md".
    - Campo retrieval_sources: URLs listadas em rag_sources.
    - Campo top_k: 5
    - Campo temperature: 0.3
  langchain:
    - Usar retriever tipo "MultiVectorRetriever" ou "HybridRetriever".
    - Armazenar embeddings em "FAISS", "Chroma" ou "Azure Cognitive Search".
    - Garantir que as respostas incluam referência à fonte oficial quando aplicável.

developer_info:
  authors:
    - name: "Reginaldo Miguel"
      role: "Arquiteto de Solução"
      contact: "https://www.linkedin.com/in/reginaldomig/"
    - name: "Nayara Lopes"
      role: "Líder de Gestão de Mudanças"
      contact: "https://www.linkedin.com/in/naylopes/"
  license: "MIT"
  last_validation: "2025-10-25"
  note: >
    Todos os links foram verificados e estavam ativos nesta data.
    Mudanças podem ocorrer conforme atualizações nos sites institucionais.
  tagline: "Ninguém se cala — porque toda voz importa."
